### ISSUE TITLE
Compiling Nightingale in Xcode under MacOS  10.11 El Capitan

### ISSUE THREAD

**Issue by MusicMouse** [AMNS/Nightingale#110]
Now that I have a Mac set up with a current OS and Xcode rev (7.3.1) I though I'd find out what happens with an Ngale built attempt in this config.

QuickDraw, which we thought would be a problem, turns out to still be supported in the current dev setup. It is still shown in Apple's online doc, qd.framework is a subframework of
ApplicationServices.framework, which see, about 3/4 of the way down
this web page (search "qd.framework" on this page):

https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html

And yes, there it is, inside the Xcode.app package:

Xcode/Contents/Developer/Platforms/MacOS.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework

Amazingly, the Carbon.framework, Xcode internal Carbon plugins etc. are all also
still there.

The errors if I try a build turn out to be from lack of the correct MacOS sdk to pick up where we let off in Snow Leopard and Xcode 3.2 though. This turned out to be fixable by downloading the version we had been using, MacOSX10.4u.sdk.tar.xz that is available here:

     https://github.com/phracker/MacOSX-SDKs/releases

and installing it within the Xcode.app package at this path:

     Xcode/Contents/Developer/Platforms/MacOS.platform/Developer/SDKs/

(Ctrl-click on the Xcode app to go inside the package to the above dir.)

Because Xcode 7.n has a limitation on backward compatibility (why on earth does Apple do this???) it is not able to find or load the 10.4 (10.4u) Mac OS sdk. This has to be fixed by making a change in the info.plist file found here:

     Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist

First change the permissions to be able to edit it then make a backup
just in case.

Then in the 9th or 10th line from the bottom of the file change the
minimum SDK version that Xcode can recognize from 10.11 to 10.4.

This can alternatively be changed from the Terminal app with:

     sudo /usr/libexec/PlistBuddy -c "Set :MinimumSDKVersion 10.4"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist

With the appropriate build settings in the project Nightingale now compiles with a small number of syntax errors.

- Laurie

**Comment by MusicMouse** [comment]
On compiling there were 2 label errors in the file NavServices.cp. They turned out not to be jumps to label beyond the scope of the case statement as the compiler thought, but just lack of necessary bracketing within the case above each default case label. Easily fixed.

There turned out to be a very few additional errors. I replaced the goto label "broken:" in About.cp with the same code that is run after the jump to that label.

There are 3 more errors to fix, all in Menu.cp, all in the routine "FixTestMenu()" within a conditional compile "#ifndef PUBLIC_VERSION". If that's residual code we can comment it out but I don't know if that conditionality is important to the project. These 3 errors are each a "Character too large for enclosing character literal type", on these statements:

     if (clickMode==ClickErase)
			SetItemMark(testMenu, TS_ClickErase, '‚Ä¢');

Do we need that function? 

All other files are compiling without errors.

**Comment by MusicMouse** [comment]
I found and selected an option to "Continue building after errors" in Xcode 7's Preferences "General" tab. So I am now able to say that there are still a total of 30 errors.

Several are the same symantic problem "Cannot jump from switch statement to case label" that I clarified to the compile by extra brackets before.

In particular the compiler is having trouble with the nested case statements in Check.cp, accounting for 7 of the 30 errors. Maybe there is a less confusing (to the compiler) way to write this? There are several more of this same error in DialogsEditor.cp.

Several more are this same lexical preprocessor type "Character too large for enclosing character literal type".

There is a linker error "cannot parse debug map" and the build process ends with an exit from the linker.

Because the rest of the errors might require more knowledge or either the the history or the intent of some of the code (conditional compiles or whatever), I think at this point I should start another branch in the GitHub repository so you can take a look at them. I did fix or work around a very few additional errors, marking most of those places with this comment line that you can search for:

     // -ls

- Laurie

**Comment by MusicMouse** [comment]
Now that we have a new branch to play around with in Xcode 7 there are 2 pending questions not answered in the previous flurry of messages.

1.

What is the compilation conditional "#ifndef PUBLIC_VERSION" used for? Is the function FixTestMenu() used? I have commented it out in the new El Capitan compatible branch of the repository to get a compile because I suspect it may be just for for temporary or test use but I could be wrong about that.

2.

I suspect that all the compiler errors on each of the lines with th cryptic-looking chars and strings (such as (ch=='"' ? '‚Äù' : '‚Äô'); CharWidth('‚Ä¶'); and the like) might disappear if these chars are represented in a different way. What are these? How do they work? How does Xcode prefer char and string literals be expressed?

**Comment by MusicMouse** [comment]
Not sure if this should be a new issue but it pertains to this thread so I'll post it here. When github compares develop, which I cloned and used, with the El Capitan branch it doesn't find differences:

https://github.com/AMNS/Nightingale/compare/develop...ElCapitan-compatible

But when I use BBEdit's Find Differences function it correctly shows the differences between the 2 repositories in these files:

About.cp
CheckMerge.cp
DrawObject.cp
DurationPopUP.cp
FileInput.cp
Info.plist
Menu.cp
NavServices.cp
project.pbxproj

Most of these are changes I made to .cp source code to resolve compile errors. Some are project settings. There are are too many differences between the source code of the 2 branches to take time to list them all individually here. But please know that these repositories are not identical as GitHub's diff would indicate.

**Comment by donbyrd** [comment]
I'm confused. In your email of 3:07 PM, you said "What's up there [in the ElCapitan-compatible branch] is the same as in /develop/, not the new prom I emailed you as "Nightingale-ElCapitan-compat.zip". As I explained in my email reply of a few minutes ago, that's exactly what'd expect, since I simply cloned develop to create ElCapitan-compatible, and I haven't yet added in any of your changes. But just above you seem to be saying that, while GitHub thinks the two branches are identical, BBEdit shows they're not. But of course you can't directly compare branches with BBEdit! Did you download both of them this afternoon and then use BBEdit on them, or did you just compare what was already on your disk, or what?

**Comment by MusicMouse** [comment]
Looks like we had a small misunderstanding. I assumed you'd be starting the new repo with the code I sent you that nearly compiles in Xocde 7.  The ones that I did the BBEdit diff on were the /develop/ clone on my Mac and the El Capitan dir also on my hard drive. I seem to have no way to push my changed files onto GitHub.

I'd upload the changed version of the source and proj settings files but I have looked all over both in my email archive and on the GitHub site for the invitation to become a member of the project you said you sent but haven't found it. Definitely feeling perplexed. :-(

**Comment by MusicMouse** [comment]
Found it! And accepted the invitation. Should be able to upload the changed files tonight or tomorrow.

So all's cool, though if you have time, maybe you could respond on those 2 pending questions above (conditional on "#ifndef PUBLIC_VERSION", is FixTestMenu() still nec or can stay commented out, and what are those cryptic chars/strings?).

**Comment by donbyrd** [comment]
Re our "small misunderstanding", my plan was and is to start by cloning _develop_, then substituting all your files. Why not just start with all your files? Because I wasn't sure you sent me a complete set. Of course SourceTree would have told me if that was the case, so I probably just made things more complex, especially by confusing you. Sorry. Anyway, I'm not sure where things stand at the moment, but I should after looking at your other messages and comments, and taking a quick look at the repository. Since you're now a member (I just checked, and you are! congrats), yes, you should able to upload the changes, but I'll try to do it tonight unless you already have.

I don't have time to think about the FixTestMenu() question right now -- I can't stay up much longer -- but will try to remember tomorrow! Please remind me if I don't.

**Comment by MusicMouse** [comment]
I did try to figure out how to upload the files but everything I wanted to try seemed to prefer to connect to /master/ which obviously I didn't want to overwrite. I'll have to work on the source control config and figure it out. Much safer if you do the uploads and syncs on this.

In addition to the source files the actual project file with the settings I used should be uploaded too I think. I have played with the build and other settings a bit since though and it doesn't seem to make a lot of difference.

Re: those 2 questions, I have also had problems in the Music Mouse code with jumping to #defined labels I was using as case names within switch() statements. This is something we need to figure out, though a workaround would be to use the constants rather than the #defines.

For the other problem, the chars that don't fit, maybe using character literals (e.g. '\xF8') would get us a compile.

This is all I can do on this at the moment though I'd love to go on playing around with this all. I had a great time playing hooky from other stuff I was supposed to be doing, which I rationalize by it being the last week of August.

It should not be a rush or a pressure on you. If I've made it feel like it is that's just because this is exciting and fun. I also hope it will turn out to be helpful.

TBC!

**Comment by MusicMouse** [comment]
The keycodes are in HIToolbox/Events.h

**Comment by donbyrd** [comment]
Thanks for finding the key codes; that should help with the compiler errors on the lines with cryptic-looking chars and strings!

You asked what the compilation conditional "#ifndef PUBLIC_VERSION" was for. It's a holdover from when Ngale was a commercial product and we had a beta version with debugging features built in, including a "Test" menu, and a PUBLIC_VERSION without them. So the FixTestMenu() function _is_ needed. We should probably get rid of all of the PUBLIC_VERSION #ifdef's and #ifndef's, but I'm not ready to yet.

**Comment by MusicMouse** [comment]
For the moment, FixTestMenu() is commented out in the ElCap NGale files. I want to see wha hap if we can get a full compile, so we know what awaits at the linker stage of the process.

I wonder if something might be different in how Xcode handles #define statements from earlier versions. The switch case labels that don't work in either NGale or MM and that function have #defines in common. (Just a late at night hairbrained thought.)

- Laurie (by iPad)

**Comment by MusicMouse** [comment]
Re: using nag keycodes, whether to use them depends on whether you want to refer to a location on the physical keyboard or to a specific alphabetical character.

I remember when writing Music Mouse having to decide which to use because the foreign language keyboards have the letters in different physical locations. Did I want to preserve the physical layout of the MM instrument under the player's hand or the alphabetical associations with the words for what the keys controlled?

- Laurie (by iPad)

**Comment by donbyrd** [comment]
I've copied the discussion of key codes above, which is really not specific to compiling with Xcode 7.x, to the new issue that GitHub helpfully added a reference to (#112). Another one of GitHub's really nice features, I think! Anyway, please put any further comments on key codes there; this thread has gotten awfully long, and I'd like to keep it as well-focused as possible.

**Comment by donbyrd** [comment]
Re FixTestMenu() and #defines, your observation that "The switch case labels that don't work in either NGale or MM and that function have #defines in common" is very interesting. Offhand, I find it hard to believe that's the explanation. The syntax and semantics of #define, #ifdef, and #ifndef are very straightforward, and -- as far as I know -- always have been. That is, as long as you don't use #undef. I just checked Ngale, and I'm unhappy to see that the code _does_ have a few #undefs, but I don't see how any of them could possibly affect the cases we're talking about, and even if they did, the effect would just be to swap the effects of #ifdef and #ifndef.

Still, maybe there's an indirect connection to #define!

**Comment by MusicMouse** [comment]
No prob with spinning off a separate threat re: keycodes. I had thought they fell under the El Capitan / Xcode 7 thread because there wasn't a problem with those chars in earlier compilers.

I agree #define seems about as basic rock bottom foundational and immutable as can be. Can you think of another reason why the recent compilers are not willing to accept a #defined label as a case name in a switch?

You probably want this under a different thread too. Not being accustomed to GitHub I find it more convenience to have this all in a single thread so I can use the browser's "Find" to quickly locate any sub-subjet on the discussion page (when in browser instead of in email of course).

Nonetheless glad to follow your lead in how to use these collaborative tools, being a newbee.

**Comment by MusicMouse** [comment]
Possible fix for those "can't jump to label" errors in the various switch statements:

"A jump to a labelled statement (case xxx and default are labelled statements) is not permitted to bypass the initialisation of an object a variable."

from http://www.cplusplus.com/forum/general/168196/

The fix it to do what I did in some of the files when we started a few months ago: Initialize all the variables referenced within the switch cases before any of them.

**Comment by donbyrd** [comment]
Re your next-to-last message, I thought key codes should be in a separate threat -- uh, thread :-) -- because they've been causing compilation warnings (though not fatal errors) for years… and not always functioning properly, e.g., on my MacBook, the <enter> key doesn't dismiss the text-entry dialog.

Re #defines, I haven't thought about this at all yet; hopefully today.

And putting stuff in separate threads means specific issues can have labels attached -- "bug", "feature request", "serious", etc. -- assigned to someone to work on, and marked _closed_ at the appropriate time! You can still search because GitHub lets you search all issues for a word or phrase; ask me if you don't see how.

**Comment by donbyrd** [comment]
Re 'those "can't jump to label" errors in the various switch statements': Bravo, Laurie! Or maybe I should say: Shame on you, Don! Since you pointed it out a couple of months ago, I should have thought of this.

This explains the error in About.cp involving an explicit _goto_ as well as the switch stmts.

Yes, one fix is to initialize all the variables referenced within the switch cases before any of them. One that I think is better in many cases, and what you actually did for some of the switches, is to shrink the scope of the variables in question by adding curly brackets.
