### ISSUE TITLE
MIDI Files Type 0

### ISSUE THREAD

**Issue by MusicMouse** [AMNS/Nightingale#129]
Wanted to import several MIDI tracks I had previously created int Nglae but it only accepts Type 1 MIDI files. Type 0 are very simple single channel tracks. Maybe the additional specifications in a Type 1 file could simple be defaulted to enable import of Type 0.

The reason I want to do this in NGale is the use of open meter, better able to avoid or minutes mize the morass of quantization error all other notation software produces.

**Comment by MusicMouse** [comment]
(Sorry about to many typos. Was sent too quickly from my phone.)

**Comment by donbyrd** [comment]
This duplicates #128. (That explains the typos!)
