### ISSUE TITLE
Using loops for timed delays is embarrassing

### ISSUE THREAD

**Issue by donbyrd** [AMNS/Nightingale#70]
Nightingale still uses loops for timed delays. We did this originally because the old Mac toolbox offered only 1/60th of a sec. resolution, not good enough for some of our needs, but it's embarrassing now; it never worked well, and it's been obsolete for 20 years, if not longer!

**Comment by donbyrd** [comment]
See discussion here:
http://stackoverflow.com/questions/5362577/c-gettimeofday-for-computing-time

Some people recommend gettimeofday(), but then there's this:

"gettimeofday actually should not be used to measure the elapsed time. Use clock_gettime(CLOCK_MONOTONIC) instead. _Here's why_ – Daniel Kamil Kozar"

**Comment by MusicMouse** [comment]
These will ultimately need to be replaced by Obj C timer callbacks anyway.

**Comment by donbyrd** [comment]
Really? Standard C/C++ library functions won't work? Oh, you must mean because of what Ngale uses them for, mostly controlling timing of MIDI playback. You've clearly thought more about this than I have!

**Comment by donbyrd** [comment]
But another application of a timing function, the one I'm interested in at the moment, is for user-interface purposes, e.g., to leave a message on the screen for a certain period of time, or -- for debugging -- to make a function stop dead after drawing something before continuing. For that, we need wall-clock time, not processor time. clock() is no good for that, since it gives processor time; gettimeofday() returns wall-clock time.

**Comment by donbyrd** [comment]
Fixed in 5.7b10 with commit 6c667ee, using gettimeofday().
