### ISSUE TITLE
Xcode 2.5 (at least) can't save certain source files

### ISSUE THREAD

**Issue by donbyrd** [AMNS/Nightingale#94]
This is utterly bizarre, but for a long time, Xcode 2.5 on my G5 has been unable to save two or three (I think) source-code files. One I'm certain of is a problem is Browser.cp.

**Comment by MusicMouse** [comment]
If you do a cmd-i on those files in the Finder, those files don't turn out to be locked do they?

Regardless, can you copy and paste their content into a new file in BBEdit and save each of those files from there?

- Laurie (by iPad)

**Comment by donbyrd** [comment]
No, they're not locked. I've been opening them in BBEdit (not copying and pasting, though that'd surely work as well) and editing and saving them with it for months, with no problems at all. I haven't tried with Xcode 3.2 yet. I'm starting to think it's a problem with the Xcode project.

**Comment by donbyrd** [comment]
Dragging.cp seems also to have this problem. Maybe removing them from the project and re-adding them would fix this?

**Comment by donbyrd** [comment]
No, removing them and re-adding by itself doesn't help -- but re-adding and telling Xcode the correct encoding (according to BBEdit) does the trick!
